---
title: "DV_RProject1"
output: html_document
---
 This is the HTML page for Dr. Cannata's Data Visualization class' Project 1.  
 
 1. The first thing I did was create a private Git Repository called DV_RProject1 and clone it into my Data Visualization folder.  
 
 2. I then created an RStudio project and the subfolders '00 Doc', '01 Data', and '02 Visualizations'.  
 3. In '00 Doc' I created the Rmd file that outputted this html page and started writing about following instructions.  

 4. I then copied and pasted the SQL query given to us by Dr. Cannata into my Oracle Database query builder to create the Titanic Data Tables. 
 
 5. I then loaded the required packages and copied the SQL statement given in Titanic Analysis.R into my DataFrame.R file 
 
 6. Lastly, I manipulated the r code ggplot function to create the 6 six plots.
 
 7.  For my unique plot I plotted PASSENGER ID and TICKET NUMBER because I thought that they would be correlated.  I.E. John bought ticket number 1 and is passenger number 1 but I was wrong.




```{r} 
source("../01\ Data/DataFrame.R", echo = TRUE)
```


